#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://47.104.186.204:3306/zk_bucket?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
#spring.datasource.username=reduce_weight_flyway
#spring.datasource.password=jdzO1cx*S1%iEsck
##主数据库
spring:
  readSize: 2
  master:
    datasource:
      jdbcUrl: jdbc:mysql://192.168.188.132:3339/test?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  slave1:
    datasource:
      jdbcUrl: jdbc:mysql://192.168.188.132:3340/test?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  slave2:
    datasource:
      jdbcUrl: jdbc:mysql://192.168.188.132:3341/test?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  #应用访问地址(需要能被认证中心正常访问)
  cas:
    server-name: http://localhost:8087/demo
  #认证中心服务地址
    cas-server-url-prefix: http://localhost:8080
  #认证中心登录地址
    cas-server-login-url: ${spring.cas.cas-server-url-prefix}/login
  #认证中心登出地址
    cas-server-logout-url: ${spring.cas.cas-server-url-prefix}/logout?service=${spring.cas.server-name}
  #正则表达式，定义无需认证中心拦截的地址(需要保留原登录页时使用，否则无需配置)
  #spring.cas.ignore-pattern=(login|register|\.js|\.img|\.css)(\?.*)?$

  #spring security 过滤器排序
  security:
    filter:
      order: -100
  #spring security 安全过滤器责任链拦截的分发类型,也就是需要拦截哪些请求，这里面包括同步，错误，请求，转发，包含
      dispatcher-types: async,error,request
#密码编码器的钥匙
#system.user.password.secret=uvwxyz
#用户相关配置
#spring.security.user.name=user
#spring.security.user.password=123456
#spring.security.user.roles=ADMIN

server:
  port: 8087
  servlet:
    context-path: /demo